# https://github.com/pages-themes/minimal

theme: jekyll-theme-minimal

title: A-Detector
description: An anomaly-based intrusion detection system. 
logo: /assets/images/logo.png?raw=true
show_downloads: true
google_analytics: UA-102345837-2
