# https://github.com/pages-themes/minimal

theme: jekyll-theme-minimal

title: A-Detector
description: An anomaly-based intrusion detection system. 
logo: https://pages-themes.github.io/minimal/assets/img/logo.png
show_downloads: true
google_analytics: 
